orgName: paritytech
dockerTag: from-gitlab-vars
processbot:
  config:
    KUBE_NAMESPACE: processbot
    WEBHOOK_PORT: 8080
  secret: 
    PROCESSBOT_KEY: from-gitlab-vars
    BAMBOO_TOKEN: from-gitlab-vars
    MATRIX_ACCESS_TOKEN: from-gitlab-vars
    WEBHOOK_SECRET: from-gitlab-vars
    GITLAB_PRIVATE_TOKEN: from-gitlab-vars
